<?php

namespace App\adms\Controllers\Services;

use App\adms\Models\Repository\ButtonPermissionUserRepository;
use App\adms\Models\Repository\MenuPermissionUserRepository;
use App\adms\Models\Repository\UsersAccessLevelsRepository;

class PageLayoutService
{
    public function configurePageElements(array $data): array
    {
        // Array com os itens de menu
        $menu = [
            'Dashboard',
            // Ordem alfabética
            'CashFlow',
            'CompletedTrainingsMatrix',
            'CostCenterSummary',
            'CreateInventoryAdjust',
            'CreateInventoryEntry',
            'CreateInventoryExit',
            'CreateInventoryItem',
            'CreateInventoryUnit',
            'CreateInventoryCategory',
            'CreateInventoryTransfer',
            'EmailConfig',
            'ExportPdfCashFlow',
            'FinancialReport',
            'FlowCashCompetence',
            'GetQuestionsByModel',
            'HistoricoAvaliacoes',
            // Sistema de Avaliações (Novo)
            'AnswerEvaluation',
            'AssignEvaluation',
            'CancelEvaluationAssignment',
            'CreateEvaluationModelWithQuestions',
            'DeleteEvaluationModel',
            'EvaluationHistory',
            'ListEvaluationAssignments',
            'UpdateEvaluationModel',
            'ViewEvaluationModel',
            'ViewEvaluationResult',
            'PrintEvaluationResult',
            'PrintEvaluationBlank',
            'LgpdAipd',
            'LgpdAipdCreate',
            'LgpdAipdDelete',
            'LgpdAipdEdit',
            'LgpdAipdSuggest',
            'LgpdAipdTemplateEducacao',
            'LgpdAipdTemplateEcommerce',
            'LgpdAipdTemplateFinanceiro',
            'LgpdAipdTemplateJuridico',
            'LgpdAipdTemplateLogistica',
            'LgpdAipdTemplateMarketing',
            'LgpdAipdTemplateRh',
            'LgpdAipdTemplateSaude',
            'LgpdAipdTemplateTelecom',
            'LgpdAipdView',
            'LgpdBasesLegais',
            'LgpdBasesLegaisCreate',
            'LgpdBasesLegaisDelete',
            'LgpdBasesLegaisEdit',
            'LgpdBasesLegaisView',
            'LgpdCategoriasTitulares',
            'LgpdCategoriasTitularesCreate',
            'LgpdCategoriasTitularesDelete',
            'LgpdCategoriasTitularesEdit',
            'LgpdCategoriasTitularesView',
            'LgpdClassificacoesDados',
            'LgpdClassificacoesDadosCreate',
            'LgpdClassificacoesDadosDelete',
            'LgpdClassificacoesDadosEdit',
            'LgpdClassificacoesDadosView',
            'LgpdConsentimentoColeta',
            'LgpdConsentimentoColetaProcessar',
            'LgpdConsentimentoEmail',
            'LgpdConsentimentoEmailProcessar',
            'LgpdConsentimentos',
            'LgpdConsentimentosCreate',
            'LgpdConsentimentosDelete',
            'LgpdConsentimentosEdit',
            'LgpdConsentimentosView',
            'LgpdDataMapping',
            'LgpdDataMappingCreate',
            'LgpdDataMappingCreateFromRopa',
            'LgpdDataMappingDelete',
            'LgpdDataMappingEdit',
            'LgpdDataMappingView',
            'LgpdDashboard',
            'LgpdFinalidades',
            'LgpdFinalidadesCreate',
            'LgpdFinalidadesDelete',
            'LgpdFinalidadesEdit',
            'LgpdFinalidadesView',
            'LgpdInventory',
            'LgpdInventoryCreate',
            'LgpdInventoryDelete',
            'LgpdInventoryEdit',
            'LgpdInventoryView',
            'ListLogAcessos',
            'ListLogAlteracoes',
            'LgpdRipd',
            'LgpdRipdCreate',
            'LgpdRipdDashboard',
            'LgpdRipdDelete',
            'LgpdRipdEdit',
            'LgpdRipdExportPdf',
            'LgpdRipdExportPdfList',
            'LgpdRipdExportPdfView',
            'LgpdRipdView',
            'LgpdRopa',
            'LgpdRopaCreate',
            'LgpdRopaCreateFromInventory',
            'LgpdRopaDelete',
            'LgpdRopaEdit',
            'LgpdRopaView',
            'LgpdTiposDados',
            'LgpdTiposDadosCreate',
            'LgpdTiposDadosDelete',
            'LgpdTiposDadosEdit',
            'LgpdTiposDadosView',
            'LgpdTia',
            'LgpdTiaCreate',
            'LgpdTiaDashboard',
            'LgpdTiaDelete',
            'LgpdTiaEdit',
            'LgpdTiaExportPdf',
            'LgpdTiaExportPdfList',
            'LgpdTiaExportPdfView',
            'LgpdTiaTemplate',
            'LgpdTiaTemplateFinanceiro',
            'LgpdTiaTemplateMarketing',
            'LgpdTiaTemplateRh',
            'LgpdTiaTemplateTi',
            'LgpdTiaTemplates',
            'LgpdWorkflowReport',
            'ListAccessLevels',
            'ListAccountsPlan',
            'ListBanks',
            'ListBranches',
            'ListCostCenters',
            'ListCustomers',
            'ListDepartments',
            'ListDocuments',
            'ListInventoryItems',
            'ListInventoryUnits',
            'ListInventoryCategories',
            'ListInventoryStocks',
            'ListInventoryPositions',
            'UpdateInventoryUnit',
            'UpdateInventoryCategory',
            'UpdateInventoryStock',
            'UpdateInventoryPosition',
            'ListEvaluationAnswers',
            'ListEvaluationModels',
            'ListEvaluationQuestions',
            'ListGroupsPages',
            'ListInformativos',
            'ListMovBetweenAccounts',
            'ListPages',
            'ListPackages',
            'ListPaymentMethods',
            'ListPayments',
            'ListPositions',
            'ListReceipts',
            'CreateCustomer',
            'CreateStrategicIndicator',
            'CreateStrategicPlan',
            'CreateSupplier',
            'DeleteCustomer',
            'DeleteStrategicIndicator',
            'DeleteStrategicPlan',
            'DeleteSupplier',
            'EditStrategicIndicator',
            'EditStrategicPlan',
            'ListStrategicIndicators',
            'ListStrategicPlans',
            'ListSuppliers',
            'StrategicDashboard',
            'StrategicIndicatorsCreate',
            'StrategicIndicatorsEdit',
            'StrategicIndicatorsList',
            'UpdateCustomer',
            'UpdateStrategicIndicator',
            'UpdateStrategicPlan',
            'UpdateSupplier',
            'ViewCustomer',
            'ViewStrategicIndicator',
            'ViewStrategicPlan',
            'ViewSupplier',
            'ViewPlanIndicators',
            'ListTrainings',
            'ListTrainingStatus',
            'ListUsers',
            'OrganizationChart',
            'MatrixByUser',
            'MenuEstoque',
            'Movements',
            'MyEvaluations',
            'Notificacoes',
            'PasswordPolicy',
            'ScheduleTraining',
            'SendNotification',
            'TestNotification',
            'TrainingDashboard',
            'TrainingKpiDashboard',
            'TrainingMatrixManager',
            'UpdateTrainingMatrix',
            'UpdateInventoryItem',
            'ReportInventoryBalance',
            'ReportInventoryHistory',
            'ExportInventoryBalanceCsv',
            'ExportInventoryHistoryCsv',
            'DeleteInventoryUnit',
            'DeleteInventoryCategory',
            'DeleteInventoryStock',
            'DeleteInventoryPosition',
            'ViewEvaluationAnswer',
            'ViewInventoryItem',
            'WhatsAppConfig',
            'SaveWhatsAppConfig',
            'TestWhatsAppConfig',
            // CRM - Gestão de Relacionamento com Clientes
            'CrmDashboard',
            'CrmKanbanPipeline',
            // Parceiros
            'CrmListPartners',
            'CrmCreatePartner',
            'CrmViewPartner',
            'CrmUpdatePartner',
            'CrmDeletePartner',
            // Oportunidades
            'CrmListOpportunities',
            'CrmCreateOpportunity',
            'CrmViewOpportunity',
            'CrmUpdateOpportunity',
            'CrmDeleteOpportunity',
            'CrmMoveOpportunity',
            'CrmGenerateProposalPdf',
            // Atividades
            'CrmListActivities',
            'CrmViewActivity',
            'CrmCreateActivity',
            'CrmUpdateActivity',
            'CrmCompleteActivity',
            'CrmDeleteActivity',
            // Notas
            'CrmCreateNote',
            'CrmDeleteNote',
            // Documentos
            'CrmUploadDocument',
            'CrmDownloadDocument',
            'CrmDeleteDocument',
            // Tags
            'CrmListTags',
            'CrmCreateTag',
            'CrmUpdateTag',
            'CrmDeleteTag',
            // Campos Customizáveis
            'CrmListCustomFields',
            'CrmCreateCustomField',
            'CrmUpdateCustomField',
            'CrmDeleteCustomField',
            // Automações
            'CrmListAutomations',
            'CrmCreateAutomation',
            'CrmViewAutomation',
            'CrmDeleteAutomation',
            // Dashboard Gerencial
            'CrmManagerDashboard',
            // Relatórios
            'CrmReportPipeline',
            'CrmReportPerformance',
            'CrmReportConversion',
            // Import/Export
            'CrmImportPartners',
            'CrmExportPartners',
            'CrmDownloadTemplatePartners',
            'CrmImportOpportunities',
            'CrmExportOpportunities',
            'CrmDownloadTemplateOpportunities',
            // CRM - Envio WhatsApp
            'CrmSendWhatsApp',
            // Relatórios Dinâmicos
            'ListDynamicReports',
            'DynamicReportBuilder',
            'ViewDynamicReport',
            'SaveDynamicReport',
            'ExecuteDynamicReport',
            'DeleteDynamicReport',
            'ExportDynamicReportExcel',
            'ExportDynamicReportPdf',
            'ExportDynamicReportCsv',
        ];

        // Verificar se o usuário está logado
        if (!isset($_SESSION['user_id'])) {
            // Para páginas públicas sem usuário logado, retornar apenas os dados básicos
            return array_merge($data, ['menuPermission' => []]);
        }

        // Verificar se o usuário tem o nível de acesso Super Administrador.
        // Nível de acesso Super Administrador tem acesso a todos os botões, não precisa validar as permissões no banco de dados
        $usersAccessLevels = new UsersAccessLevelsRepository();
        $userAccessLevelsArray = $usersAccessLevels->getUserAccessLevelArray($_SESSION['user_id']);
        $userAccessLevelsArray = $userAccessLevelsArray ? $userAccessLevelsArray : [];
        if (in_array(1, $userAccessLevelsArray, true)) {
            // Super Administrador tem acesso a todos os botões solicitados
            $buttonPermission = new ButtonPermissionUserRepository();
            $data['buttonPermission'] = $buttonPermission->buttonPermission($data['buttonPermission'] ?? []);
            return array_merge($data, ['menuPermission' => $menu]);
        }

        // Apresentar ou ocultar botão
        $buttonPermission = new ButtonPermissionUserRepository();
        $data['buttonPermission'] = $buttonPermission->buttonPermission($data['buttonPermission'] ?? []);

        // Apresentar ou ocultar item de menu
        $menuPermission = new MenuPermissionUserRepository();
        $data['menuPermission'] = $menuPermission->menuPermission($menu);

        return $data;
    }
}
