<?php

namespace App\adms\Controllers\Services;

use App\adms\Models\Repository\ButtonPermissionUserRepository;
use App\adms\Models\Repository\MenuPermissionUserRepository;
use App\adms\Models\Repository\UsersAccessLevelsRepository;

class PageLayoutService
{
    public function configurePageElements(array $data): array
    {
        // Array com os itens de menu
        $menu = [
            'Dashboard',
            // Ordem alfabética
            'CashFlow',
            'CompletedTrainingsMatrix',
            'CostCenterSummary',
            'CreateInventoryAdjust',
            'CreateInventoryEntry',
            'CreateInventoryExit',
            'CreateInventoryItem',
            'CreateInventoryUnit',
            'CreateInventoryCategory',
            'CreateInventoryTransfer',
            'EmailConfig',
            'ExportPdfCashFlow',
            'FinancialReport',
            'FlowCashCompetence',
            'GetQuestionsByModel',
            'HistoricoAvaliacoes',
            // Sistema de Avaliações (Novo)
            'AnswerEvaluation',
            'AssignEvaluation',
            'CancelEvaluationAssignment',
            'CreateEvaluationModelWithQuestions',
            'DeleteEvaluationModel',
            'EvaluationHistory',
            'ListEvaluationAssignments',
            'UpdateEvaluationModel',
            'ViewEvaluationModel',
            'ViewEvaluationResult',
            'PrintEvaluationResult',
            'PrintEvaluationBlank',
            'LgpdAipd',
            'LgpdAipdCreate',
            'LgpdAipdDelete',
            'LgpdAipdEdit',
            'LgpdAipdSuggest',
            'LgpdAipdTemplateEducacao',
            'LgpdAipdTemplateEcommerce',
            'LgpdAipdTemplateFinanceiro',
            'LgpdAipdTemplateJuridico',
            'LgpdAipdTemplateLogistica',
            'LgpdAipdTemplateMarketing',
            'LgpdAipdTemplateRh',
            'LgpdAipdTemplateSaude',
            'LgpdAipdTemplateTelecom',
            'LgpdAipdView',
            'LgpdBasesLegais',
            'LgpdBasesLegaisCreate',
            'LgpdBasesLegaisDelete',
            'LgpdBasesLegaisEdit',
            'LgpdBasesLegaisView',
            'LgpdTermos',
            'LgpdTermosCreate',
            'LgpdTermosDelete',
            'LgpdTermosEdit',
            'LgpdTermosExportPdf',
            'LgpdTermosView',
            'LgpdCategoriasTitulares',
            'LgpdCategoriasTitularesCreate',
            'LgpdCategoriasTitularesDelete',
            'LgpdCategoriasTitularesEdit',
            'LgpdCategoriasTitularesView',
            'LgpdClassificacoesDados',
            'LgpdClassificacoesDadosCreate',
            'LgpdClassificacoesDadosDelete',
            'LgpdClassificacoesDadosEdit',
            'LgpdClassificacoesDadosView',
            'LgpdConsentimentoColeta',
            'LgpdConsentimentoColetaProcessar',
            'LgpdConsentimentoEmail',
            'LgpdConsentimentoEmailProcessar',
            'LgpdConsentimentos',
            'LgpdConsentimentosCreate',
            'LgpdConsentimentosDelete',
            'LgpdConsentimentosEdit',
            'LgpdConsentimentosView',
            'LgpdDataMapping',
            'LgpdDataMappingCreate',
            'LgpdDataMappingCreateFromRopa',
            'LgpdDataMappingDelete',
            'LgpdDataMappingEdit',
            'LgpdDataMappingView',
            'LgpdDashboard',
            'LgpdFinalidades',
            'LgpdFinalidadesCreate',
            'LgpdFinalidadesDelete',
            'LgpdFinalidadesEdit',
            'LgpdFinalidadesView',
            'LgpdInventory',
            'LgpdInventoryCreate',
            'LgpdInventoryDelete',
            'LgpdInventoryEdit',
            'LgpdInventoryView',
            'ListLogAcessos',
            'ListConnectedUsers',
            'ListLogAlteracoes',
            'LogSettings',
            'LgpdRipd',
            'LgpdRipdCreate',
            'LgpdRipdDashboard',
            'LgpdRipdDelete',
            'LgpdRipdEdit',
            'LgpdRipdExportPdf',
            'LgpdRipdExportPdfList',
            'LgpdRipdExportPdfView',
            'LgpdRipdView',
            'LgpdRopa',
            'LgpdRopaCreate',
            'LgpdRopaCreateFromInventory',
            'LgpdRopaDelete',
            'LgpdRopaEdit',
            'LgpdRopaView',
            'LgpdTiposDados',
            'LgpdTiposDadosCreate',
            'LgpdTiposDadosDelete',
            'LgpdTiposDadosEdit',
            'LgpdTiposDadosView',
            'LgpdTia',
            'LgpdTiaCreate',
            'LgpdTiaDashboard',
            'LgpdTiaDelete',
            'LgpdTiaEdit',
            'LgpdTiaExportPdf',
            'LgpdTiaExportPdfList',
            'LgpdTiaExportPdfView',
            'LgpdTiaTemplate',
            'LgpdTiaTemplateFinanceiro',
            'LgpdTiaTemplateMarketing',
            'LgpdTiaTemplateRh',
            'LgpdTiaTemplateTi',
            'LgpdTiaTemplates',
            'LgpdWorkflowReport',
            'ListAccessLevels',
            'ListAccountsPlan',
            'ListBanks',
            'ListBranches',
            'ListCostCenters',
            'ListCustomers',
            'ListDepartments',
            'ListWorkShifts',
            'CreateWorkShift',
            'ViewWorkShift',
            'UpdateWorkShift',
            'DeleteWorkShift',
            'ListDocuments',
            'ListInventoryItems',
            'ListInventoryUnits',
            'ListInventoryCategories',
            'ListInventoryStocks',
            'ListInventoryPositions',
            'ListInventoryOperations',
            'UpdateInventoryUnit',
            'UpdateInventoryCategory',
            'UpdateInventoryStock',
            'UpdateInventoryPosition',
            'ListEvaluationAnswers',
            'ListEvaluationModels',
            'ListEvaluationQuestions',
            'ListGroupsPages',
            'ListInformativos',
            'Timeline',
            'TimelineProfile',
            'TimelineMembers',
            'CreateTimelinePost',
            'TimelineModerate',
            'TimelineReport',
            'TimelineLike',
            'TimelineCommentLike',
            'TimelineViewComments',
            'TimelinePostReactions',
            'UpdateTimelinePost',
            'TimelineComment',
            'TimelineShare',
            'TimelineSearchUsers',
            'ListCompanyEvents',
            'ViewCompanyEvent',
            'CreateCompanyEvent',
            'UpdateCompanyEvent',
            'DeleteCompanyEvent',
            'CompanyEventReport',
            'EventRsvp',
            'CompanyEventsSearchUsers',
            'CompanyEventsMonth',
            // Dashboard - visibilidade de cards
            'DashboardCardInformativos',
            'DashboardCardPolicies',
            'DashboardCardTimeline',
            'DashboardCardEventos',
            'DashboardCardAniversariantes',
            'DashboardCardTempoEmpresa',
            'DashboardCardPayrollDocuments',
            'DashboardCardMyCalendar',
            'DashboardCardGamificationQuizzes',
            'DashboardCardRoomBooking',
            'ListPolicies',
            'ListMovBetweenAccounts',
            'ListPages',
            'ListPackages',
            'ListPaymentMethods',
            'ListPayments',
            'ListPositions',
            'ListReceipts',
            'CreateCustomer',
            'CreateStrategicIndicator',
            'CreateStrategicPlan',
            'CreateSupplier',
            'DeleteCustomer',
            'DeleteStrategicIndicator',
            'DeleteStrategicPlan',
            'DeleteSupplier',
            'EditStrategicIndicator',
            'EditStrategicPlan',
            'ListStrategicIndicators',
            'ListStrategicPlans',
            'ListSuppliers',
            'StrategicDashboard',
            'StrategicIndicatorsCreate',
            'StrategicIndicatorsEdit',
            'StrategicIndicatorsList',
            'UpdateCustomer',
            'UpdateStrategicIndicator',
            'UpdateStrategicPlan',
            'UpdateSupplier',
            'ViewCustomer',
            'ViewStrategicIndicator',
            'ViewStrategicPlan',
            'ViewSupplier',
            'ViewPlanIndicators',
            'ListTrainings',
            'ListTrainingStatus',
            'ListUsers',
            // Gestão de Pessoas - Políticas Internas
            'ListPolicies',
            'CreatePolicy',
            'ViewPolicy',
            'UpdatePolicy',
            'DeletePolicy',
            'AcknowledgePolicy',
            'ReadPolicy',
            'ListPolicyCategories',
            'CreatePolicyCategory',
            'UpdatePolicyCategory',
            'DeletePolicyCategory',
            'ExportUsersExcel',
            'ExportUsersPdf',
            'OrganizationChart',
            'MatrixByUser',
            'MenuEstoque',
            'Movements',
            'MyEvaluations',
            'Notificacoes',
            'PasswordPolicy',
            'ScheduleTraining',
            'SendNotification',
            'TestNotification',
            'TrainingDashboard',
            'TrainingKpiDashboard',
            'TrainingMatrixManager',
            'UpdateTrainingMatrix',
            'UpdateInventoryItem',
            'ReportInventoryBalance',
            'ReportInventoryHistory',
            'ExportInventoryBalanceCsv',
            'ExportInventoryHistoryCsv',
            'DeleteInventoryUnit',
            'DeleteInventoryCategory',
            'DeleteInventoryStock',
            'DeleteInventoryPosition',
            'ViewEvaluationAnswer',
            'ViewInventoryItem',
            'SapApiConfig',
            'SaveSapApiConfig',
            'TestSapApiConfig',
            'McpApiConfig',
            'SaveMcpApiConfig',
            'PushConfig',
            'SavePushConfig',
            'GeneratePushVapidKeys',
            'TestPushNotification',
            'WhatsAppConfig',
            'SaveWhatsAppConfig',
            'TestWhatsAppConfig',
            'McpChat',
            // CRM - Gestão de Relacionamento com Clientes
            'CrmDashboard',
            'CrmKanbanPipeline',
            // Parceiros
            'CrmListPartners',
            'CrmCreatePartner',
            'CrmViewPartner',
            'CrmUpdatePartner',
            'CrmDeletePartner',
            // Oportunidades
            'CrmListOpportunities',
            'CrmCreateOpportunity',
            'CrmViewOpportunity',
            'CrmUpdateOpportunity',
            'CrmDeleteOpportunity',
            'CrmMoveOpportunity',
            'CrmGenerateProposalPdf',
            // Atividades
            'CrmListActivities',
            'CrmViewActivity',
            'CrmCreateActivity',
            'CrmUpdateActivity',
            'CrmCompleteActivity',
            'CrmDeleteActivity',
            // Notas
            'CrmCreateNote',
            'CrmDeleteNote',
            // Gestão de Projetos
            'ListProjects',
            'CreateProject',
            'UpdateProject',
            'DeleteProject',
            'ListProjectStages',
            'CreateProjectStage',
            'UpdateProjectStage',
            'DeleteProjectStage',
            'ListStageGroups',
            'CreateStageGroup',
            'UpdateStageGroup',
            'DeleteStageGroup',
            // Documentos
            'CrmUploadDocument',
            'CrmDownloadDocument',
            'CrmDeleteDocument',
            // Tags
            'CrmListTags',
            'CrmCreateTag',
            'CrmUpdateTag',
            'CrmDeleteTag',
            // Campos Customizáveis
            'CrmListCustomFields',
            'CrmCreateCustomField',
            'CrmUpdateCustomField',
            'CrmDeleteCustomField',
            // Automações
            'CrmListAutomations',
            'CrmCreateAutomation',
            'CrmViewAutomation',
            'CrmDeleteAutomation',
            // Dashboard Gerencial
            'CrmManagerDashboard',
            // Relatórios
            'CrmReportPipeline',
            'CrmReportPerformance',
            'CrmReportConversion',
            // Import/Export
            'CrmImportPartners',
            'CrmExportPartners',
            'CrmDownloadTemplatePartners',
            'CrmImportOpportunities',
            'CrmExportOpportunities',
            'CrmDownloadTemplateOpportunities',
            // CRM - Envio WhatsApp
            'CrmSendWhatsApp',
            // Relatórios Dinâmicos (Locais e SAP)
            'ListDynamicReports',
            'ListDynamicReportsSap',
            'DynamicReportBuilder',
            'DynamicReportBuilderLocal',
            'DynamicReportBuilderSap',
            'ViewDynamicReport',
            'SaveDynamicReport',
            'ExecuteDynamicReport',
            'DeleteDynamicReport',
            'ExportDynamicReportExcel',
            'ExportDynamicReportPdf',
            'ExportDynamicReportCsv',
            // Dashboard de Vendas SAP B1
            'SalesDashboard',
            'SalesDashboardData',
            // Dashboards Personalizados
            'ListDashboards',
            'CreateDashboard',
            'EditDashboard',
            'DuplicateDashboard',
            'ViewDashboard',
            'DeleteDashboard',
            'ExecuteDashboard',
            'GetFilterOptions',
            'DashboardDataSources',
            'UploadSpreadsheet',
            'GetSpreadsheetFields',
            // Gamificação (timeline + quizzes)
            'CreateGamificationQuiz',
            'CreateGamificationQuizQuestion',
            'DeleteGamificationQuiz',
            'DeleteGamificationQuizQuestion',
            'GamificationQuizCatalog',
            'GamificationLeaderboard',
            'GamificationEngagementDashboard',
            'ListGamificationPointLedger',
            'ListGamificationQuizQuestions',
            'ListGamificationQuizzes',
            'ListGamificationTimelineRules',
            'SubmitGamificationQuizAttempt',
            'TakeGamificationQuiz',
            'UpdateGamificationQuiz',
            'UpdateGamificationQuizQuestion',
            'UpdateGamificationTimelineRule',
            // Gestão de Pessoas - Performance
            'ListPerformanceReviews',
            'CreatePerformanceReview',
            'ViewPerformanceReview',
            'UpdatePerformanceReview',
            'RecordReviewResults',
            'DeletePerformanceReview',
            'ListPerformanceGoals',
            'CreatePerformanceGoal',
            'ViewPerformanceGoal',
            'UpdatePerformanceGoal',
            'DeletePerformanceGoal',
            'ListPerformanceFeedbacks',
            'CreatePerformanceFeedback',
            'ViewPerformanceFeedback',
            'UpdatePerformanceFeedback',
            'DeletePerformanceFeedback',
            'ListRequestTypes',
            'CreateRequestType',
            'UpdateRequestType',
            'DeleteRequestType',
            'UpdateEmployeeRequest',
            'PendingApprovals',
            'ApproveEmployeeRequestManager',
            'ApproveEmployeeRequestHR',
            'ListCompetencies',
            'CreateCompetency',
            'ViewCompetency',
            'UpdateCompetency',
            'DeleteCompetency',
            'CompetencyMatrix',
            'NineBoxMatrix',
            'PerformanceDashboard',
            'ExportNineBoxMatrixPdf',
            'ExportNineBoxMatrixExcel',
            'ExportAnalysisPdf',
            'ExportAnalysisInfo',
            // Portal do Colaborador
            'EmployeePortal',
            'ImportPayrollDocuments',
            'PayrollImportBatchReport',
            'PayrollImportBatchAudit',
            'ListPayrollDocumentTypes',
            'CreatePayrollDocumentType',
            'UpdatePayrollDocumentType',
            'DeletePayrollDocumentType',
            'MyPayrollDocuments',
            'ViewPayrollDocument',
            'ViewPayrollSignedBundle',
            'ConfirmPayrollDocumentDownload',
            'SignPayrollDocument',
            'PayrollSignatureReceipt',
            'ListPayrollSigningPendencies',
            'PayrollRemindersCron',
            'PayrollCronConfig',
            'ListEmployeeRequests',
            'CreateEmployeeRequest',
            'ViewEmployeeRequest',
            'ListEmployeeTickets',
            'CreateEmployeeTicket',
            'ViewEmployeeTicket',
            // People Analytics
            'PeopleAnalytics',
            'PeopleReports',
            // Recrutamento / Currículos / Vagas
            'RhCandidatos',
            'RhCandidatosCreate',
            'RhCandidatosView',
            'RhCandidatosEdit',
            'RhCandidatosDelete',
            'RhVagas',
            'RhVagasCreate',
            'RhVagasView',
            'RhVagasEdit',
            'RhVagasDelete',
            'RhVincularCandidatoVaga',
            'RhAtualizarStatusCandidatura',
            'RhKpiDashboard',
            'RhEntrevistas',
            'RhEntrevistasCreate',
            'RhEntrevistasView',
            'RhEntrevistasEdit',
            'RhEntrevistasDelete',
            // Reserva de Salas
            'ListMeetingRooms',
            'CreateMeetingRoom',
            'ViewMeetingRoom',
            'UpdateMeetingRoom',
            'DeleteMeetingRoom',
            'RoomCalendar',
            'BookRoom',
            'CreateBooking',
            'ListBookings',
            'ViewBooking',
            'UpdateBooking',
            'CancelBooking',
            'BookingWaitlist',
            'JoinWaitlist',
            'ConfirmWaitlistBooking',
            'RoomsListRequestTypes',
            'RoomsCreateRequestType',
            'RoomsUpdateRequestType',
            'RoomsDeleteRequestType',
            'RoomsListRequestGroups',
            'RoomsCreateRequestGroup',
            'RoomsUpdateRequestGroup',
            'RoomsDeleteRequestGroup',
            'RoomsListServiceRequests',
            'RoomsCreateServiceRequest',
            'RoomsViewServiceRequest',
            'RoomsUpdateServiceRequest',
            'RoomsDeleteServiceRequest',
            'AdminBookingDashboard',
            'AdminBookings',
            'BookingReports',
            'RoomsCalendarIntegrationSettings',
            // Histórico de Emprego
            'UpdateEmploymentHistory',
            'CalendarConfig',
            'MyCalendar',
        ];

        // Verificar se o usuário está logado
        if (!isset($_SESSION['user_id'])) {
            // Para páginas públicas sem usuário logado, retornar apenas os dados básicos
            return array_merge($data, ['menuPermission' => []]);
        }

        // Níveis de acesso do usuário (cache em sessão — evita query em toda navegação)
        $userAccessLevelsArray = $_SESSION['adms_user_access_level_ids'] ?? null;
        if (!is_array($userAccessLevelsArray)) {
            $usersAccessLevels = new UsersAccessLevelsRepository();
            $userAccessLevelsArray = $usersAccessLevels->getUserAccessLevelArray((int) $_SESSION['user_id']);
            $userAccessLevelsArray = $userAccessLevelsArray ? $userAccessLevelsArray : [];
            $_SESSION['adms_user_access_level_ids'] = $userAccessLevelsArray;
        }
        $menuPermissionRepo = new MenuPermissionUserRepository();

        if (in_array(1, $userAccessLevelsArray, true)) {
            if (empty($data['buttonPermission'] ?? [])) {
                $data['buttonPermission'] = [];
            }
            $data['menuPermission'] = $menuPermissionRepo->getFilteredMenuForLayout($menu);

            return $data;
        }

        $buttonPermission = new ButtonPermissionUserRepository();
        $data['buttonPermission'] = $buttonPermission->buttonPermission($data['buttonPermission'] ?? []);
        $data['menuPermission'] = $menuPermissionRepo->getFilteredMenuForLayout($menu);

        return $data;
    }
}
