<?php

namespace App\adms\Helpers;

/**
 * Helper para Estados/Províncias de países internacionais
 */
class InternationalStatesHelper
{
    /**
     * Obter estados/províncias por código do país
     */
    public static function getStatesByCountry(string $countryCode): array
    {
        $states = [
            // Argentina
            'AR' => [
                'Buenos Aires',
                'Catamarca',
                'Chaco',
                'Chubut',
                'Córdoba',
                'Corrientes',
                'Entre Ríos',
                'Formosa',
                'Jujuy',
                'La Pampa',
                'La Rioja',
                'Mendoza',
                'Misiones',
                'Neuquén',
                'Río Negro',
                'Salta',
                'San Juan',
                'San Luis',
                'Santa Cruz',
                'Santa Fe',
                'Santiago del Estero',
                'Tierra del Fuego',
                'Tucumán',
            ],
            
            // Chile
            'CL' => [
                'Arica y Parinacota',
                'Tarapacá',
                'Antofagasta',
                'Atacama',
                'Coquimbo',
                'Valparaíso',
                'Metropolitana de Santiago',
                'O\'Higgins',
                'Maule',
                'Ñuble',
                'Biobío',
                'Araucanía',
                'Los Ríos',
                'Los Lagos',
                'Aysén',
                'Magallanes',
            ],
            
            // Colômbia
            'CO' => [
                'Amazonas',
                'Antioquia',
                'Arauca',
                'Atlántico',
                'Bogotá D.C.',
                'Bolívar',
                'Boyacá',
                'Caldas',
                'Caquetá',
                'Casanare',
                'Cauca',
                'Cesar',
                'Chocó',
                'Córdoba',
                'Cundinamarca',
                'Guainía',
                'Guaviare',
                'Huila',
                'La Guajira',
                'Magdalena',
                'Meta',
                'Nariño',
                'Norte de Santander',
                'Putumayo',
                'Quindío',
                'Risaralda',
                'San Andrés y Providencia',
                'Santander',
                'Sucre',
                'Tolima',
                'Valle del Cauca',
                'Vaupés',
                'Vichada',
            ],
            
            // Uruguai
            'UY' => [
                'Artigas',
                'Canelones',
                'Cerro Largo',
                'Colonia',
                'Durazno',
                'Flores',
                'Florida',
                'Lavalleja',
                'Maldonado',
                'Montevideo',
                'Paysandú',
                'Río Negro',
                'Rivera',
                'Rocha',
                'Salto',
                'San José',
                'Soriano',
                'Tacuarembó',
                'Treinta y Tres',
            ],
            
            // Paraguai
            'PY' => [
                'Alto Paraguay',
                'Alto Paraná',
                'Amambay',
                'Asunción',
                'Boquerón',
                'Caaguazú',
                'Caazapá',
                'Canindeyú',
                'Central',
                'Concepción',
                'Cordillera',
                'Guairá',
                'Itapúa',
                'Misiones',
                'Ñeembucú',
                'Paraguarí',
                'Presidente Hayes',
                'San Pedro',
            ],
            
            // Peru
            'PE' => [
                'Amazonas',
                'Áncash',
                'Apurímac',
                'Arequipa',
                'Ayacucho',
                'Cajamarca',
                'Callao',
                'Cusco',
                'Huancavelica',
                'Huánuco',
                'Ica',
                'Junín',
                'La Libertad',
                'Lambayeque',
                'Lima',
                'Loreto',
                'Madre de Dios',
                'Moquegua',
                'Pasco',
                'Piura',
                'Puno',
                'San Martín',
                'Tacna',
                'Tumbes',
                'Ucayali',
            ],
            
            // México
            'MX' => [
                'Aguascalientes',
                'Baja California',
                'Baja California Sur',
                'Campeche',
                'Chiapas',
                'Chihuahua',
                'Ciudad de México',
                'Coahuila',
                'Colima',
                'Durango',
                'Guanajuato',
                'Guerrero',
                'Hidalgo',
                'Jalisco',
                'México',
                'Michoacán',
                'Morelos',
                'Nayarit',
                'Nuevo León',
                'Oaxaca',
                'Puebla',
                'Querétaro',
                'Quintana Roo',
                'San Luis Potosí',
                'Sinaloa',
                'Sonora',
                'Tabasco',
                'Tamaulipas',
                'Tlaxcala',
                'Veracruz',
                'Yucatán',
                'Zacatecas',
            ],
            
            // Estados Unidos
            'US' => [
                'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
                'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
                'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
                'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
                'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
                'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
                'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
                'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
                'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
                'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming',
            ],
            
            // Canadá
            'CA' => [
                'Alberta',
                'British Columbia',
                'Manitoba',
                'New Brunswick',
                'Newfoundland and Labrador',
                'Northwest Territories',
                'Nova Scotia',
                'Nunavut',
                'Ontario',
                'Prince Edward Island',
                'Quebec',
                'Saskatchewan',
                'Yukon',
            ],
            
            // Espanha
            'ES' => [
                'Andalucía',
                'Aragón',
                'Asturias',
                'Baleares',
                'Canarias',
                'Cantabria',
                'Castilla-La Mancha',
                'Castilla y León',
                'Cataluña',
                'Comunidad Valenciana',
                'Extremadura',
                'Galicia',
                'La Rioja',
                'Madrid',
                'Murcia',
                'Navarra',
                'País Vasco',
            ],
            
            // Portugal
            'PT' => [
                'Açores',
                'Aveiro',
                'Beja',
                'Braga',
                'Bragança',
                'Castelo Branco',
                'Coimbra',
                'Évora',
                'Faro',
                'Guarda',
                'Leiria',
                'Lisboa',
                'Madeira',
                'Portalegre',
                'Porto',
                'Santarém',
                'Setúbal',
                'Viana do Castelo',
                'Vila Real',
                'Viseu',
            ],
        ];
        
        return $states[$countryCode] ?? [];
    }
}

