<?php

declare(strict_types=1);

return [
    'exames' => [
        'table' => 'adms_sst_exames',
        'singular' => 'Exame',
        'plural' => 'Exames',
        'prefix' => 'Exame',
        'url' => 'exame',
        'menu' => 'sst-list-exames',
        'icon' => 'fa-stethoscope',
        'type' => 'catalog',
        'fields' => [
            'nome' => ['label' => 'Nome', 'type' => 'text', 'required' => true],
            'descricao' => ['label' => 'Descrição', 'type' => 'textarea'],
            'periodicidade_meses' => ['label' => 'Periodicidade (meses)', 'type' => 'number'],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Ativo', 'Inativo']],
        ],
        'list_cols' => ['id', 'nome', 'periodicidade_meses', 'status'],
    ],
    'epis' => [
        'table' => 'adms_sst_epis',
        'singular' => 'EPI',
        'plural' => 'EPIs',
        'prefix' => 'Epi',
        'url' => 'epi',
        'menu' => 'sst-list-epis',
        'icon' => 'fa-hard-hat',
        'type' => 'catalog',
        'fields' => [
            'nome' => ['label' => 'Nome', 'type' => 'text', 'required' => true],
            'descricao' => ['label' => 'Descrição', 'type' => 'textarea'],
            'ca_numero' => ['label' => 'Nº CA', 'type' => 'text'],
            'ca_validade' => ['label' => 'Validade CA', 'type' => 'date'],
            'estoque_atual' => ['label' => 'Estoque atual', 'type' => 'number'],
            'estoque_minimo' => ['label' => 'Estoque mínimo', 'type' => 'number'],
            'periodicidade_troca_dias' => ['label' => 'Troca (dias)', 'type' => 'number'],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Ativo', 'Inativo']],
        ],
        'list_cols' => ['id', 'nome', 'ca_numero', 'estoque_atual', 'status'],
    ],
    'riscos' => [
        'table' => 'adms_sst_riscos',
        'singular' => 'Risco',
        'plural' => 'Riscos',
        'prefix' => 'Risco',
        'url' => 'risco',
        'menu' => 'sst-list-riscos',
        'icon' => 'fa-exclamation-triangle',
        'type' => 'catalog',
        'fields' => [
            'nome' => ['label' => 'Nome', 'type' => 'text', 'required' => true],
            'descricao' => ['label' => 'Descrição', 'type' => 'textarea'],
            'tipo' => ['label' => 'Tipo', 'type' => 'text'],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Ativo', 'Inativo']],
        ],
        'list_cols' => ['id', 'nome', 'tipo', 'status'],
    ],
    'cids' => [
        'table' => 'adms_sst_cids',
        'singular' => 'CID',
        'plural' => 'CIDs',
        'prefix' => 'Cid',
        'url' => 'cid',
        'menu' => 'sst-list-cids',
        'icon' => 'fa-notes-medical',
        'type' => 'catalog',
        'no_view' => true,
        'fields' => [
            'codigo' => ['label' => 'Código', 'type' => 'text', 'required' => true],
            'descricao' => ['label' => 'Descrição', 'type' => 'text', 'required' => true],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Ativo', 'Inativo']],
        ],
        'list_cols' => ['id', 'codigo', 'descricao', 'status'],
    ],
    'medicos' => [
        'table' => 'adms_sst_medicos',
        'singular' => 'Médico',
        'plural' => 'Médicos',
        'prefix' => 'Medico',
        'url' => 'medico',
        'menu' => 'sst-list-medicos',
        'icon' => 'fa-user-md',
        'type' => 'catalog',
        'no_view' => true,
        'fields' => [
            'nome' => ['label' => 'Nome', 'type' => 'text', 'required' => true],
            'crm' => ['label' => 'CRM', 'type' => 'text'],
            'crm_uf' => ['label' => 'UF CRM', 'type' => 'text'],
            'clinica' => ['label' => 'Clínica', 'type' => 'text'],
            'telefone' => ['label' => 'Telefone', 'type' => 'text'],
            'email' => ['label' => 'E-mail', 'type' => 'email'],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Ativo', 'Inativo']],
        ],
        'list_cols' => ['id', 'nome', 'crm', 'clinica', 'status'],
    ],
    'asos' => [
        'table' => 'adms_sst_asos',
        'singular' => 'ASO',
        'plural' => 'ASOs',
        'prefix' => 'Aso',
        'url' => 'aso',
        'menu' => 'sst-list-asos',
        'icon' => 'fa-file-medical',
        'type' => 'employee',
        'has_anexos' => true,
        'fields' => [
            'adms_user_id' => ['label' => 'Colaborador', 'type' => 'user', 'required' => true],
            'adms_sst_exame_id' => ['label' => 'Exame', 'type' => 'fk_exame'],
            'adms_sst_medico_id' => ['label' => 'Médico', 'type' => 'fk_medico'],
            'tipo' => ['label' => 'Tipo', 'type' => 'select', 'options' => ['Admissional', 'Periódico', 'Mudança de função', 'Retorno ao trabalho', 'Demissional'], 'required' => true],
            'data_realizacao' => ['label' => 'Data realização', 'type' => 'date', 'required' => true],
            'data_validade' => ['label' => 'Validade', 'type' => 'date'],
            'resultado' => ['label' => 'Resultado', 'type' => 'select', 'options' => ['Apto', 'Inapto', 'Apto com restrição']],
            'restricoes' => ['label' => 'Restrições', 'type' => 'textarea'],
            'clinica' => ['label' => 'Clínica', 'type' => 'text'],
            'observacoes' => ['label' => 'Observações', 'type' => 'textarea'],
        ],
        'list_cols' => ['id', 'colaborador_nome', 'tipo', 'data_realizacao', 'data_validade', 'resultado'],
    ],
    'afastamentos' => [
        'table' => 'adms_sst_afastamentos',
        'singular' => 'Afastamento',
        'plural' => 'Afastamentos',
        'prefix' => 'Afastamento',
        'url' => 'afastamento',
        'menu' => 'sst-list-afastamentos',
        'icon' => 'fa-procedures',
        'type' => 'employee',
        'has_anexos' => true,
        'fields' => [
            'adms_user_id' => ['label' => 'Colaborador', 'type' => 'user', 'required' => true],
            'adms_sst_cid_id' => ['label' => 'CID', 'type' => 'fk_cid'],
            'adms_sst_medico_id' => ['label' => 'Médico', 'type' => 'fk_medico'],
            'tipo' => ['label' => 'Tipo', 'type' => 'select', 'options' => ['Doença', 'Acidente de trabalho', 'Licença', 'Maternidade', 'Outro']],
            'data_inicio' => ['label' => 'Data início', 'type' => 'date', 'required' => true],
            'data_fim' => ['label' => 'Data fim', 'type' => 'date'],
            'dias_afastamento' => ['label' => 'Dias', 'type' => 'number'],
            'data_retorno' => ['label' => 'Data retorno', 'type' => 'date'],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Ativo', 'Encerrado']],
            'observacoes' => ['label' => 'Observações', 'type' => 'textarea'],
        ],
        'list_cols' => ['id', 'colaborador_nome', 'tipo', 'data_inicio', 'data_fim', 'status'],
    ],
    'epi_entregas' => [
        'table' => 'adms_sst_epi_entregas',
        'singular' => 'Entrega de EPI',
        'plural' => 'Entregas de EPI',
        'prefix' => 'EpiEntrega',
        'url' => 'epi-entrega',
        'menu' => 'sst-list-epi-entregas',
        'icon' => 'fa-hand-holding',
        'type' => 'employee',
        'has_anexos' => true,
        'fields' => [
            'adms_user_id' => ['label' => 'Colaborador', 'type' => 'user', 'required' => true],
            'adms_sst_epi_id' => ['label' => 'EPI', 'type' => 'fk_epi', 'required' => true],
            'tipo_movimento' => ['label' => 'Movimento', 'type' => 'select', 'options' => ['Entrega', 'Devolução', 'Substituição', 'Perda/Dano']],
            'quantidade' => ['label' => 'Quantidade', 'type' => 'number'],
            'data_movimento' => ['label' => 'Data', 'type' => 'date', 'required' => true],
            'data_prevista_troca' => ['label' => 'Prev. troca', 'type' => 'date'],
            'termo_assinado' => ['label' => 'Termo assinado', 'type' => 'checkbox'],
            'observacoes' => ['label' => 'Observações', 'type' => 'textarea'],
        ],
        'list_cols' => ['id', 'colaborador_nome', 'epi_nome', 'tipo_movimento', 'data_movimento'],
    ],
    'acidentes' => [
        'table' => 'adms_sst_acidentes',
        'singular' => 'Acidente/Incidente',
        'plural' => 'Acidentes e Incidentes',
        'prefix' => 'Acidente',
        'url' => 'acidente',
        'menu' => 'sst-list-acidentes',
        'icon' => 'fa-ambulance',
        'type' => 'employee',
        'has_anexos' => true,
        'fields' => [
            'adms_user_id' => ['label' => 'Colaborador', 'type' => 'user', 'required' => true],
            'adms_sst_cid_id' => ['label' => 'CID', 'type' => 'fk_cid'],
            'tipo' => ['label' => 'Tipo', 'type' => 'select', 'options' => ['Acidente', 'Incidente', 'Quase acidente']],
            'data_ocorrencia' => ['label' => 'Data/hora', 'type' => 'datetime', 'required' => true],
            'local' => ['label' => 'Local', 'type' => 'text'],
            'descricao' => ['label' => 'Descrição', 'type' => 'textarea', 'required' => true],
            'cat_numero' => ['label' => 'Nº CAT', 'type' => 'text'],
            'cat_data' => ['label' => 'Data CAT', 'type' => 'date'],
            'investigacao' => ['label' => 'Investigação', 'type' => 'textarea'],
            'plano_acao' => ['label' => 'Plano de ação', 'type' => 'textarea'],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Aberto', 'Em investigação', 'Encerrado']],
        ],
        'list_cols' => ['id', 'colaborador_nome', 'tipo', 'data_ocorrencia', 'status'],
    ],
    'epi_necessidade' => [
        'table' => 'adms_sst_epi_necessidade',
        'singular' => 'Necessidade de EPI',
        'plural' => 'Necessidades de EPI',
        'prefix' => 'EpiNecessidade',
        'url' => 'epi-necessidade',
        'menu' => 'sst-list-epi-necessidade',
        'icon' => 'fa-list-check',
        'type' => 'rule',
        'no_view' => true,
        'fields' => [
            'adms_position_id' => ['label' => 'Cargo', 'type' => 'fk_position'],
            'adms_department_id' => ['label' => 'Departamento', 'type' => 'fk_department'],
            'adms_sst_risco_id' => ['label' => 'Risco', 'type' => 'fk_risco'],
            'adms_sst_epi_id' => ['label' => 'EPI', 'type' => 'fk_epi', 'required' => true],
            'obrigatorio' => ['label' => 'Obrigatório', 'type' => 'checkbox'],
            'observacoes' => ['label' => 'Observações', 'type' => 'textarea'],
        ],
        'list_cols' => ['id', 'cargo_nome', 'departamento_nome', 'epi_nome', 'obrigatorio'],
    ],
    'exame_necessidade' => [
        'table' => 'adms_sst_exame_necessidade',
        'singular' => 'Necessidade de Exame',
        'plural' => 'Necessidades de Exame',
        'prefix' => 'ExameNecessidade',
        'url' => 'exame-necessidade',
        'menu' => 'sst-list-exame-necessidade',
        'icon' => 'fa-clipboard-list',
        'type' => 'rule',
        'no_view' => true,
        'fields' => [
            'adms_position_id' => ['label' => 'Cargo', 'type' => 'fk_position'],
            'adms_department_id' => ['label' => 'Departamento', 'type' => 'fk_department'],
            'adms_sst_risco_id' => ['label' => 'Risco', 'type' => 'fk_risco'],
            'adms_sst_exame_id' => ['label' => 'Exame', 'type' => 'fk_exame', 'required' => true],
            'periodicidade_meses' => ['label' => 'Periodicidade (meses)', 'type' => 'number'],
            'obrigatorio' => ['label' => 'Obrigatório', 'type' => 'checkbox'],
            'observacoes' => ['label' => 'Observações', 'type' => 'textarea'],
        ],
        'list_cols' => ['id', 'cargo_nome', 'departamento_nome', 'exame_nome', 'periodicidade_meses'],
    ],
    'riscos_cargo' => [
        'table' => 'adms_sst_riscos_cargo',
        'singular' => 'Risco por Cargo',
        'plural' => 'Riscos por Cargo',
        'prefix' => 'RiscoCargo',
        'url' => 'risco-cargo',
        'menu' => 'sst-list-risco-cargo',
        'icon' => 'fa-shield-virus',
        'type' => 'rule',
        'no_view' => true,
        'fields' => [
            'adms_position_id' => ['label' => 'Cargo', 'type' => 'fk_position'],
            'adms_department_id' => ['label' => 'Departamento', 'type' => 'fk_department'],
            'adms_sst_risco_id' => ['label' => 'Risco', 'type' => 'fk_risco', 'required' => true],
            'nivel' => ['label' => 'Nível', 'type' => 'select', 'options' => ['Baixo', 'Médio', 'Alto', 'Crítico']],
            'observacoes' => ['label' => 'Observações', 'type' => 'textarea'],
        ],
        'list_cols' => ['id', 'cargo_nome', 'departamento_nome', 'risco_nome', 'nivel'],
    ],
];
