<?php use App\adms\Helpers\CSRFHelper; $form = $this->data['form'] ?? []; ?>
<div class="container-fluid px-4"><div class="card shadow-sm mt-4"><div class="card-header"><h1 class="h4 mb-0">Cadastrar autorização</h1></div><div class="card-body">
<?php if (!empty($this->data['errors'])): ?><div class="alert alert-danger"><?= implode('<br>', array_map('htmlspecialchars', $this->data['errors'])) ?></div><?php endif; ?>
<form method="post"><input type="hidden" name="csrf_token" value="<?= CSRFHelper::generateCSRFToken('form_portaria_autorizacao') ?>"><div class="row g-3">
<div class="col-md-6"><label class="form-label">Visitante *</label><select required class="form-select" name="visitante_id"><option value="">Selecione</option><?php foreach (($this->data['visitantes'] ?? []) as $v): ?><option value="<?= (int) $v['id'] ?>" <?= (int) ($form['visitante_id'] ?? 0) === (int) $v['id'] ? 'selected' : '' ?>><?= htmlspecialchars((string) $v['nome']) ?><?= !empty($v['documento']) ? ' — ' . htmlspecialchars((string) $v['documento']) : '' ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label">Anfitrião *</label><select required class="form-select" name="anfitriao_user_id"><option value="">Selecione</option><?php foreach (($this->data['usuarios'] ?? []) as $u): ?><option value="<?= (int) $u['id'] ?>" <?= (int) ($form['anfitriao_user_id'] ?? 0) === (int) $u['id'] ? 'selected' : '' ?>><?= htmlspecialchars((string) $u['name']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-4"><label class="form-label">Departamento de destino</label><select class="form-select" name="destino_departamento_id"><option value="">Selecione</option><?php foreach (($this->data['departamentos'] ?? []) as $d): ?><option value="<?= (int) $d['id'] ?>" <?= (int) ($form['destino_departamento_id'] ?? 0) === (int) $d['id'] ? 'selected' : '' ?>><?= htmlspecialchars((string) $d['name']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-4"><label class="form-label">Origem</label><select class="form-select" name="origem"><option value="agendada">Agendada</option><option value="nao_programada" <?= ($form['origem'] ?? '') === 'nao_programada' ? 'selected' : '' ?>>Não programada</option></select></div><div class="col-md-4"><label class="form-label">Tipo</label><select class="form-select" name="tipo"><option value="periodo">Período</option><option value="recorrente" <?= ($form['tipo'] ?? '') === 'recorrente' ? 'selected' : '' ?>>Recorrente</option></select></div>
<div class="col-md-3"><label class="form-label">Data inicial *</label><input required type="date" class="form-control" name="data_inicio" value="<?= htmlspecialchars((string) ($form['data_inicio'] ?? '')) ?>"></div><div class="col-md-3"><label class="form-label">Data final *</label><input required type="date" class="form-control" name="data_fim" value="<?= htmlspecialchars((string) ($form['data_fim'] ?? '')) ?>"></div><div class="col-md-3"><label class="form-label">Hora inicial</label><input type="time" class="form-control" name="hora_inicio" value="<?= htmlspecialchars((string) ($form['hora_inicio'] ?? '')) ?>"></div><div class="col-md-3"><label class="form-label">Hora final</label><input type="time" class="form-control" name="hora_fim" value="<?= htmlspecialchars((string) ($form['hora_fim'] ?? '')) ?>"></div>
<div class="col-md-8"><label class="form-label">Motivo</label><input class="form-control" name="motivo" value="<?= htmlspecialchars((string) ($form['motivo'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Placa do veículo</label><input class="form-control" name="veiculo_placa" value="<?= htmlspecialchars((string) ($form['veiculo_placa'] ?? '')) ?>"></div><div class="col-md-6"><label class="form-label">Dias permitidos</label><input class="form-control" name="dias_permitidos" placeholder="1,2,3,4,5" value="<?= htmlspecialchars((string) ($form['dias_permitidos'] ?? '')) ?>"></div><div class="col-12"><label class="form-label">Observações</label><textarea class="form-control" name="observacoes"><?= htmlspecialchars((string) ($form['observacoes'] ?? '')) ?></textarea></div>
</div><div class="mt-3"><a class="btn btn-secondary" href="<?= $_ENV['URL_ADM'] ?>portaria-autorizacoes">Voltar</a> <button class="btn btn-success">Criar autorização</button></div></form></div></div></div>
